name: find_a_spot
description: "An application to share and find great spots."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true